name: Glox

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Test
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install golang.org/x/tools/cmd/stringer@latest
          make stubs
          make test
        working-directory: ./glox/

